#!/bin/sh
#
# prerm script for sleepi3-dkms
#
# see: dh_installdeb(1)

set -e

DKMS_NAME=sleepi3
DKMS_VERSION=1.0.0

case "$1" in
    remove|upgrade|deconfigure)
        if [ "$(dkms status $DKMS_NAME/$DKMS_VERSION)" ]; then
            dkms remove $DKMS_NAME/$DKMS_VERSION --all > /dev/null
        fi
    ;;
esac

#DEBHELPER#

exit 0

